name: integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare linux environments
      run: |
        sudo apt-get update
        sudo apt-get install -y fuse git
        git config --global user.email "vfsfusepytest@github.com"
        git config --global user.name "vfsfusepytest"
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Build package
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel build
        python -m build --sdist --wheel --outdir dist/
    - name: Install dependencies
      run: |
        pip install dist/*.whl
    - name: Run integration tests
      run: |
        ./tests/integration/test_file_operations.sh
