name: lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Black Code Formatter
      uses: psf/black@stable
      with:
        options: "--check"
        src: "vfsfusepy"
